### ISSUE TITLE
Algo follower node crashes periodically

### ISSUE THREAD

**Issue by records88** [algorand/conduit#156]
**with logs like this**

`{"__type":"importer","_name":"algod","level":"error","msg":"called waitForRoundWithTimeout: wrong round returned from status for round: retrieved(32919745) != expected(32919746): status2.LastRound mismatch: context deadline exceeded"`

**Who had this? how to fix ?**

**here is the conduind config**

```
log-level: INFO
retry-count: 10
retry-delay: "1s"
hide-banner: false
metrics:
    mode: OFF
    addr: ":9999"
    prefix: "conduit"
importer:
    name: algod
    config:
        mode: "follower"
        netaddr: "http://algo:18720"
        token: "algo_not_admin_token"
        catchup-config:
            admin-token: "algo_admin_token"
processors:
exporter:
    name: postgresql
    config:
        connection-string: "host=algorand.db port=5432 user=algorand password=algo_pass dbname=algoranddb sslmode=disable"
        max-conn: 20
        delete-task:
            interval: 0
            rounds: 100000
telemetry:
  enabled: false

```
